fruits = []
F1 = input("enter fruit name: ")
fruits.append(F1)
F2 = input("enter fruit name: ")
fruits.append(F2)
F3 = input("enter fruit name: ")
fruits.append(F3)
F4 = input("enter fruit name: ")
fruits.append(F4)
F5 = input("enter fruit name: ")
fruits.append(F5)
F6 = input("enter fruit name: ")
fruits.append(F6)
F7 = input("enter fruit name: ")
fruits.append(F7)
print(fruits)